# Generated by Django 3.1.5 on 2021-07-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prodname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(),
        ),
    ]
