# Generated by Django 2.2 on 2021-07-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_auto_20210728_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='images/product0.png', max_length=1000),
        ),
    ]
